export const WRS_PHONEME_MAP = {
  "Consonants": [
    { "phoneme": "b", "graphemes": ["b"], "introduced": "1.1", "keyword": "bat" },
    { "phoneme": "k", "graphemes": ["c"], "introduced": "1.1", "keyword": "cat" },
    { "phoneme": "d", "graphemes": ["d"], "introduced": "1.1", "keyword": "dog" },
    { "phoneme": "f", "graphemes": ["f"], "introduced": "1.1", "keyword": "fun" },
    { "phoneme": "g", "graphemes": ["g"], "introduced": "1.1", "keyword": "game" },
    { "phoneme": "h", "graphemes": ["h"], "introduced": "1.1", "keyword": "hat" },
    { "phoneme": "j", "graphemes": ["j"], "introduced": "1.1", "keyword": "jug" },
    { "phoneme": "k", "graphemes": ["k"], "introduced": "1.1", "keyword": "kite" },
    { "phoneme": "l", "graphemes": ["l"], "introduced": "1.1", "keyword": "lamp" },
    { "phoneme": "m", "graphemes": ["m"], "introduced": "1.1", "keyword": "man" },
    { "phoneme": "n", "graphemes": ["n"], "introduced": "1.1", "keyword": "nut" },
    { "phoneme": "p", "graphemes": ["p"], "introduced": "1.1", "keyword": "pan" },
    { "phoneme": "r", "graphemes": ["r"], "introduced": "1.1", "keyword": "rat" },
    { "phoneme": "s", "graphemes": ["s"], "introduced": "1.1", "keyword": "snake" },
    { "phoneme": "t", "graphemes": ["t"], "introduced": "1.1", "keyword": "top" },
    { "phoneme": "k", "graphemes": ["ck"], "introduced": "1.2", "keyword": "sock" },
    { "phoneme": "ks", "graphemes": ["x"], "introduced": "1.2", "keyword": "fox" },
    { "phoneme": "kw", "graphemes": ["qu"], "introduced": "1.2", "keyword": "queen" },
    { "phoneme": "sh", "graphemes": ["sh"], "introduced": "1.2", "keyword": "ship" },
    { "phoneme": "th", "graphemes": ["th"], "introduced": "1.2", "keyword": "thumb" },
    { "phoneme": "v", "graphemes": ["v"], "introduced": "1.2", "keyword": "van" },
    { "phoneme": "w", "graphemes": ["w"], "introduced": "1.2", "keyword": "wind" },
    { "phoneme": "wh", "graphemes": ["wh"], "introduced": "1.2", "keyword": "whistle" },
    { "phoneme": "y", "graphemes": ["y"], "introduced": "1.2", "keyword": "yellow" },
    { "phoneme": "z", "graphemes": ["z"], "introduced": "1.2", "keyword": "zebra" },
    { "phoneme": "ch", "graphemes": ["ch"], "introduced": "1.3", "keyword": "chin" },
    { "phoneme": "z", "graphemes": ["s"], "introduced": "1.3", "keyword": "bugs" },
    { "phoneme": "s", "graphemes": ["c"], "introduced": "7.1", "keyword": "cent" },
    { "phoneme": "j", "graphemes": ["g"], "introduced": "7.1", "keyword": "gym" },
    { "phoneme": "j", "graphemes": ["dge"], "introduced": "7.2", "keyword": "fudge" },
    { "phoneme": "ch", "graphemes": ["tch"], "introduced": "7.3", "keyword": "catch" },
    { "phoneme": "f", "graphemes": ["ph"], "introduced": "7.3", "keyword": "phone" },
    { "phoneme": "y", "graphemes": ["i"], "introduced": "11.5", "keyword": "million" },
    { "phoneme": "g", "graphemes": ["gh"], "introduced": "12.2", "keyword": "ghost" },
    { "phoneme": "m", "graphemes": ["mb"], "introduced": "12.2", "keyword": "lamb" },
    { "phoneme": "m", "graphemes": ["mn"], "introduced": "12.2", "keyword": "column" },
    { "phoneme": "n", "graphemes": ["gn"], "introduced": "12.2", "keyword": "gnat" },
    { "phoneme": "n", "graphemes": ["kn"], "introduced": "12.2", "keyword": "knife" },
    { "phoneme": "r", "graphemes": ["rh"], "introduced": "12.2", "keyword": "rhyme" },
    { "phoneme": "r", "graphemes": ["wr"], "introduced": "12.2", "keyword": "wrist" },
    { "phoneme": "k", "graphemes": ["ch"], "introduced": "12.4", "keyword": "chorus" },
    { "phoneme": "k", "graphemes": ["que"], "introduced": "12.4", "keyword": "clique" }
  ],
  "Short Vowels": [
    { "phoneme": "ă", "graphemes": ["a"], "introduced": "1.1", "keyword": "apple" },
    { "phoneme": "ĭ", "graphemes": ["i"], "introduced": "1.1", "keyword": "itch" },
    { "phoneme": "ŏ", "graphemes": ["o"], "introduced": "1.1", "keyword": "octopus" },
    { "phoneme": "ĕ", "graphemes": ["e"], "introduced": "1.2", "keyword": "Ed" },
    { "phoneme": "ŭ", "graphemes": ["u"], "introduced": "1.2", "keyword": "up" },
    { "phoneme": "ĭv", "graphemes": ["ive"], "introduced": "4.4", "keyword": "give" },
    { "phoneme": "ə", "graphemes": ["a"], "introduced": "5.5", "keyword": "Alaska" },
    { "phoneme": "ə", "graphemes": ["i"], "introduced": "5.5", "keyword": "animal" },
    { "phoneme": "ĕ", "graphemes": ["ea"], "introduced": "9.6", "keyword": "bread" },
    { "phoneme": "ĭ", "graphemes": ["y"], "introduced": "11.1", "keyword": "gym" }
  ],
  "Welded Sounds": [
    { "phoneme": "ôl", "graphemes": ["all"], "introduced": "1.4", "keyword": "ball" },
    { "phoneme": "am", "graphemes": ["am"], "introduced": "1.5", "keyword": "ham" },
    { "phoneme": "an", "graphemes": ["an"], "introduced": "1.5", "keyword": "fan" },
    { "phoneme": "ang", "graphemes": ["ang"], "introduced": "2.1", "keyword": "fang" },
    { "phoneme": "ank", "graphemes": ["ank"], "introduced": "2.1", "keyword": "bank" },
    { "phoneme": "ing", "graphemes": ["ing"], "introduced": "2.1", "keyword": "ring" },
    { "phoneme": "ink", "graphemes": ["ink"], "introduced": "2.1", "keyword": "pink" },
    { "phoneme": "ong", "graphemes": ["ong"], "introduced": "2.1", "keyword": "song" },
    { "phoneme": "onk", "graphemes": ["onk"], "introduced": "2.1", "keyword": "honk" },
    { "phoneme": "ung", "graphemes": ["ung"], "introduced": "2.1", "keyword": "lung" },
    { "phoneme": "unk", "graphemes": ["unk"], "introduced": "2.1", "keyword": "junk" },
    { "phoneme": "īld", "graphemes": ["ild"], "introduced": "2.3", "keyword": "wild" },
    { "phoneme": "īnd", "graphemes": ["ind"], "introduced": "2.3", "keyword": "find" },
    { "phoneme": "ōld", "graphemes": ["old"], "introduced": "2.3", "keyword": "cold" },
    { "phoneme": "ōlt", "graphemes": ["olt"], "introduced": "2.3", "keyword": "colt" },
    { "phoneme": "ōst", "graphemes": ["ost"], "introduced": "2.3", "keyword": "post" },
    { "phoneme": "shŭn", "graphemes": ["tion"], "introduced": "7.4", "keyword": "vacation" },
    { "phoneme": "shŭn", "graphemes": ["sion"], "introduced": "7.4", "keyword": "mansion" },
    { "phoneme": "zhŭn", "graphemes": ["sion"], "introduced": "7.4", "keyword": "television" },
    { "phoneme": "chü", "graphemes": ["tu"], "introduced": "12.5", "keyword": "spatula" },
    { "phoneme": "chẽr", "graphemes": ["ture"], "introduced": "12.5", "keyword": "departure" },
    { "phoneme": "shəl", "graphemes": ["tial"], "introduced": "12.5", "keyword": "partial" },
    { "phoneme": "shəl", "graphemes": ["cial"], "introduced": "12.5", "keyword": "special" },
    { "phoneme": "shən", "graphemes": ["cian"], "introduced": "12.5", "keyword": "magician" },
    { "phoneme": "shənt", "graphemes": ["tient"], "introduced": "12.5", "keyword": "patient" },
    { "phoneme": "shənt", "graphemes": ["cient"], "introduced": "12.5", "keyword": "ancient" },
    { "phoneme": "shəs", "graphemes": ["tious"], "introduced": "12.5", "keyword": "cautious" },
    { "phoneme": "shəs", "graphemes": ["cious"], "introduced": "12.5", "keyword": "precious" },
    { "phoneme": "shẽr", "graphemes": ["sure"], "introduced": "12.5", "keyword": "pressure" },
    { "phoneme": "zhẽr", "graphemes": ["sure"], "introduced": "12.5", "keyword": "closure" }
  ],
  "Long Vowels": [
    { "phoneme": "ā", "graphemes": ["a"], "introduced": "5.1", "keyword": "acorn" },
    { "phoneme": "ē", "graphemes": ["e"], "introduced": "5.1", "keyword": "me" },
    { "phoneme": "ī", "graphemes": ["i"], "introduced": "5.1", "keyword": "hi" },
    { "phoneme": "ō", "graphemes": ["o"], "introduced": "5.1", "keyword": "no" },
    { "phoneme": "ū", "graphemes": ["u"], "introduced": "5.1", "keyword": "pupil" },
    { "phoneme": "ü", "graphemes": ["u"], "introduced": "5.1", "keyword": "flu" },
    { "phoneme": "ī", "graphemes": ["y"], "introduced": "5.1", "keyword": "cry" },
    { "phoneme": "ē", "graphemes": ["y"], "introduced": "5.3", "keyword": "baby" },
    { "phoneme": "ā", "graphemes": ["ai"], "introduced": "9.1", "keyword": "bait" },
    { "phoneme": "ā", "graphemes": ["ay"], "introduced": "9.1", "keyword": "play" },
    { "phoneme": "ē", "graphemes": ["ee"], "introduced": "9.2", "keyword": "jeep" },
    { "phoneme": "ē", "graphemes": ["ey"], "introduced": "9.2", "keyword": "valley" },
    { "phoneme": "ō", "graphemes": ["oa"], "introduced": "9.3", "keyword": "boat" },
    { "phoneme": "ō", "graphemes": ["oe"], "introduced": "9.3", "keyword": "toe" },
    { "phoneme": "ū", "graphemes": ["ue"], "introduced": "9.3", "keyword": "rescue" },
    { "phoneme": "ü", "graphemes": ["ue"], "introduced": "9.3", "keyword": "blue" },
    { "phoneme": "ō", "graphemes": ["ow"], "introduced": "9.5", "keyword": "snow" },
    { "phoneme": "ü", "graphemes": ["oo"], "introduced": "9.5", "keyword": "school" },
    { "phoneme": "ü", "graphemes": ["ou"], "introduced": "9.5", "keyword": "soup" },
    { "phoneme": "ā", "graphemes": ["ea"], "introduced": "9.6", "keyword": "steak" },
    { "phoneme": "ē", "graphemes": ["ea"], "introduced": "9.6", "keyword": "eat" },
    { "phoneme": "ū", "graphemes": ["eu"], "introduced": "9.7", "keyword": "feud" },
    { "phoneme": "ū", "graphemes": ["ew"], "introduced": "9.7", "keyword": "few" },
    { "phoneme": "ü", "graphemes": ["eu"], "introduced": "9.7", "keyword": "deuce" },
    { "phoneme": "ü", "graphemes": ["ew"], "introduced": "9.7", "keyword": "chew" },
    { "phoneme": "ü", "graphemes": ["ui"], "introduced": "9.7", "keyword": "suit" },
    { "phoneme": "ī", "graphemes": ["y"], "introduced": "11.1", "keyword": "type" },
    { "phoneme": "ā", "graphemes": ["eigh"], "introduced": "11.3", "keyword": "eight" },
    { "phoneme": "ī", "graphemes": ["igh"], "introduced": "11.3", "keyword": "light" },
    { "phoneme": "ā", "graphemes": ["ei"], "introduced": "11.4", "keyword": "vein" },
    { "phoneme": "ē", "graphemes": ["ei"], "introduced": "11.4", "keyword": "ceiling" },
    { "phoneme": "ē", "graphemes": ["ie"], "introduced": "11.4", "keyword": "piece" },
    { "phoneme": "ē", "graphemes": ["i"], "introduced": "11.5", "keyword": "champion" }
  ],
  "Vowel-Consonant-e": [
    { "phoneme": "ā", "graphemes": ["a-e"], "introduced": "4.1", "keyword": "safe" },
    { "phoneme": "ē", "graphemes": ["e-e"], "introduced": "4.1", "keyword": "Pete" },
    { "phoneme": "ī", "graphemes": ["i-e"], "introduced": "4.1", "keyword": "pine" },
    { "phoneme": "ō", "graphemes": ["o-e"], "introduced": "4.1", "keyword": "home" },
    { "phoneme": "ū", "graphemes": ["u-e"], "introduced": "4.1", "keyword": "mule" },
    { "phoneme": "ü", "graphemes": ["u-e"], "introduced": "4.1", "keyword": "rule" }
  ],
  "Diphthongs": [
    { "phoneme": "ô", "graphemes": ["au"], "introduced": "9.4", "keyword": "August" },
    { "phoneme": "ô", "graphemes": ["aw"], "introduced": "9.4", "keyword": "saw" },
    { "phoneme": "oi", "graphemes": ["oi"], "introduced": "9.4", "keyword": "coin" },
    { "phoneme": "oy", "graphemes": ["oy"], "introduced": "9.4", "keyword": "boy" },
    { "phoneme": "oo", "graphemes": ["oo"], "introduced": "9.5", "keyword": "book" },
    { "phoneme": "ou", "graphemes": ["ou"], "introduced": "9.5", "keyword": "trout" },
    { "phoneme": "ou", "graphemes": ["ow"], "introduced": "9.5", "keyword": "plow" },
    { "phoneme": "ô", "graphemes": ["a"], "introduced": "12.3", "keyword": "squash, wash" }
  ],
  "R-Controlled": [
    { "phoneme": "ar", "graphemes": ["ar"], "introduced": "8.1", "keyword": "car" },
    { "phoneme": "ẽr", "graphemes": ["er"], "introduced": "8.1", "keyword": "her" },
    { "phoneme": "ẽr", "graphemes": ["ir"], "introduced": "8.1", "keyword": "bird" },
    { "phoneme": "or", "graphemes": ["or"], "introduced": "8.1", "keyword": "horn" },
    { "phoneme": "ẽr", "graphemes": ["ur"], "introduced": "8.1", "keyword": "burn" },
    { "phoneme": "ẽr", "graphemes": ["ar"], "introduced": "8.5", "keyword": "beggar, wizard" },
    { "phoneme": "ẽr", "graphemes": ["or"], "introduced": "8.5", "keyword": "doctor" },
    { "phoneme": "or", "graphemes": ["ar"], "introduced": "12.3", "keyword": "warm" },
    { "phoneme": "ẽr", "graphemes": ["or"], "introduced": "12.3", "keyword": "worm" }
  ]
};
